#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jan 27 16:11:44 IST 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_time_impl -key {Post-Implementation:sim_1:Timing:test} -tclbatch test.tcl -view /users/btech/rohitv23/assignment3_monday1/test_time_impl.wcfg -log simulate.log"
xsim test_time_impl -key {Post-Implementation:sim_1:Timing:test} -tclbatch test.tcl -view /users/btech/rohitv23/assignment3_monday1/test_time_impl.wcfg -log simulate.log

