# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_3/design_3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_processing_system7_0_0/design_3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_processing_system7_0_0 || ORIG_REF_NAME==design_3_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_myip2_0_0/design_3_myip2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_myip2_0_0 || ORIG_REF_NAME==design_3_myip2_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_ps7_0_axi_periph_0/design_3_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_rst_ps7_0_100M_0/design_3_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_auto_pc_0 || ORIG_REF_NAME==design_3_auto_pc_0} -quiet] -quiet

# XDC: /users/btech/rohitv23/assignment_1/assignment_1.gen/sources_1/bd/design_3/design_3_ooc.xdc
